import sys
import pandas as pd
from scipy import stats

def main():
    """
    Statistical signficance testing of samples values generated by training and evaluating against reported metrics
    """
    if len(sys.argv) < 2:
        print("USAGE: python t-test.py [cleaneval|web2text]")
        sys.exit()

    split = "cleaneval"
    df = pd.read_csv(f"random_cleaneval.csv")


    # TODO: should we take unary values or "normal" ones?

    # Results taken from paper
    metrics = {
            "cleaneval": {
                "accuracy": 0.84,
                "precision": 0.88,
                "recall":0.85,
                "f1":0.86
            },
            "web2text": {
                "accuracy": 0.86,
                "precision": 0.87,
                "recall":0.90,
                "f1":0.88
            }
    }

    metrics_of_split = metrics[split]

    for key, val in metrics_of_split.items():
        print(f"{key}: {stats.ttest_1samp(df[key], val)}")


    



if __name__ == '__main__':
  main()